In [1]:
#matrix operation using vectorization
import numpy as np

a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

add=a+b
sub=a-b
mul=a*b
trans=a.T
dot=a@b

print("Matrix a:\n", a)
print("Matrix b:\n", b)

print("\nAddition:\n",add)
print("\nSubtraction:\n",sub)
print("\nMultiplication:\n",mul)
print("\nTranspose:\n",trans)
print("\nDot product:\n",dot)



Matrix a:
 [[1 2]
 [3 4]]
Matrix b:
 [[5 6]
 [7 8]]

Addition:
 [[ 6  8]
 [10 12]]

Subtraction:
 [[-4 -4]
 [-4 -4]]

Multiplication:
 [[ 5 12]
 [21 32]]

Transpose:
 [[1 3]
 [2 4]]

Dot product:
 [[19 22]
 [43 50]]


In [6]:
#with SVD
import numpy as np
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
U,S,VT = np.linalg.svd(X)
n_components = 2
X_reconstructed = np.dot(U[:,:n_components],np.dot(np.diag(S[:n_components]),VT[:n_components,:]))
print("Og Matrix:")
print(X)
print("\nReconstructed Matrix (with reduced dimensions):")
print(X_reconstructed)

Og Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Reconstructed Matrix (with reduced dimensions):
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
